<?php

namespace WeatherBundle\Repository;

use WeatherBundle\Entity\Town;
use WeatherBundle\Entity\UsersTowns;

/**
 * UsersTownsRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UsersTownsRepository extends \Doctrine\ORM\EntityRepository
{
    public function checkUserTown(int $userId, int $townId)
    {
        $qb = $this->createQueryBuilder('ut');
        return $qb
            ->andWhere('ut.userId = :userId')
            ->andWhere('ut.townId = :townId')
            ->setParameter('userId', $userId)
            ->setParameter('townId', $townId)
            ->getQuery();
    }

    public function myTowns(int $userId)
    {
        $db = $this->createQueryBuilder('ut');
        return $db
            ->select('t')
            ->join(Town::class, 't', 'WITH', 't.id = ut.townId')
            ->andWhere('ut.userId = :userId')
            ->setParameter('userId', $userId)
            ->getQuery()
        ;
    }

    public function removeUserTown(int $userId, int $townId)
    {
        $qb = $this->createQueryBuilder('ut');
        $qb->delete('WeatherBundle:UsersTowns', 'ut')
            ->andWhere('ut.userId = :userId')
            ->andWhere('ut.townId = :townId')
            ->setParameter('userId', $userId)
            ->setParameter('townId', $townId)
            ->getQuery()
            ->execute()
        ;
    }

}
